# Site settings
title: "Claudi & Thomas - Hochzeit 2018"
email: thjaeckle@gmail.com
url: https://thjaeckle.github.io/private-wed/
description: "Diese Seite dient der Hochzeitsplanung und -vorbereitung von Claudi und Thomas"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#ffffff'
  links: '#219ab3'

# Footer settings
footer: Thomas Jäckle

# Build settings
markdown: kramdown
permalink: pretty
