# Site settings
title: "Wir trauen uns"
email: hochzeit@jaeckle.rocks
url: https://thjaeckle.github.io/private-wed/
description: "Claudi & Thomas - Hochzeit 2018"

# Color settings
color:
  #primary-dark: '#82CFFD'
  primary-dark: '#669BC3'
  links: '#F0FFFF'

# Footer settings
footer: Thomas Jäckle & Claudia Brandt

# Build settings
markdown: kramdown
permalink: pretty
